name: Linting

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  fourmolu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - uses: haskell-actions/run-fourmolu@v11
      with:
        version: "0.18.0.0"
        pattern: |
          app/**/*.hs
          src/**/*.hs
          test/**/*.hs

  hlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: 'Set up HLint'
      uses: haskell-actions/hlint-setup@v2
      with:
        version: '3.10'

    - name: 'Run HLint'
      uses: haskell-actions/hlint-run@v2
      with:
        path: '["app/", "src/", "test/"]'
        fail-on: warning
